spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-microservice
          predicates:
            - Path=/api/products/**
        - id: user-service
          uri: lb://user-microservice
          predicates:
            - Path=/api/users/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
