server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://mohamedaziz-idoudi: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@github.com/mohamedaziz-idoudi/config-server.git
          clone-on-start: true
          branch: main

